#!/bin/bash
N=10
if [ "x$1" = "x" ]; then
	a=4
	num=$N
else
	a=$1
	if [ "x$2" = "x" ]; then
		num=$N
	else
		num=$2
	fi
fi
i=1
while [ $i -le $a ]; do
	python3 generator.py -f test$i.txt -c $num -m $num
	echo "test$i.txt generated"
	let i=i+1
done

